name: Jenkins_trigger_build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
#       run : echo "Hello world"
#       run: |
#           curl -i --user Aishwarya:11ffbd89d6a2b90e0abb9ecb0cf6d991f0 \
#           -X POST \
#           -H "Content-Type: application/json" \
#           -H "Jenkins-Crumb: CRUMB" \
#           -H "Jenkins-Crumb: true" \
#           http://192.168.1.6:8080/job/checklist/build
      run : curl -i -X POST --user Aishwarya:11ffbd89d6a2b90e0abb9ecb0cf6d991f0 http://192.168.1.6:8080/job/checklist/build
# #       env:
# #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
